{
 "title": "Simulation SUMO",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 10 Congested Streets (by Unique Vehicle Count)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  streetname,\r\n  COUNT(DISTINCT entity_id) AS \"number_of_vehicles\"\r\nFROM\r\n  mtsumo_digital_twin.etvehicle\r\nWHERE\r\n  $__timeFilter(time_index)\r\n  AND streetname IS NOT NULL\r\n  AND streetname NOT LIKE ':%'\r\n  AND streetname !~ '^[0-9\\s]+$'\r\nGROUP BY\r\n  streetname\r\nORDER BY\r\n  number_of_vehicles DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Total number of vehicules",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_vehicles\r\nFROM mtsumo_digital_twin.etvehicle\r\nWHERE time_index > NOW() - INTERVAL '30 seconds';\r\n"
    }
   ]
  },
  {
   "title": "Evolution of trafffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(time_index, $__interval) AS \"time\",\r\n  COUNT(*) AS vehicles\r\nFROM\r\n  mtsumo_digital_twin.etvehicle\r\nWHERE\r\n  $__timeFilter(time_index)\r\nGROUP BY\r\n  1 -- Group by the first column (\"time\")\r\nORDER BY\r\n  1; -- Order by the first column"
    }
   ]
  },
  {
   "title": "Waiting time analysis",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', time_index) AS bucket,\r\n       AVG(waitingtime) AS avg_waiting\r\nFROM mtsumo_digital_twin.etvehicle\r\nWHERE time_index > NOW() - INTERVAL '30 minutes'\r\nGROUP BY bucket\r\nORDER BY bucket;\r\n"
    }
   ]
  },
  {
   "title": "Pollution Hotspots Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_index AS \"time\", -- Needed for filtering\r\n  co2emission,\r\n  latitude(location_centroid) AS \"lat\",\r\n  longitude(location_centroid) AS \"lon\" -- Your geo_point column\r\nFROM\r\n  mtsumo_digital_twin.etvehicle\r\nWHERE\r\n  $__timeFilter(time_index)"
    }
   ]
  },
  {
   "title": "GeoMap of Hay Hassani",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    time_index AS \"time\",\r\n    entity_id AS \"vehicle_id\",\r\n    latitude(location_centroid) AS \"lat\",\r\n    longitude(location_centroid) AS \"lon\",\r\n    speed,\r\n    waitingtime,\r\n    co2emission\r\nFROM mtsumo_digital_twin.etvehicle\r\nWHERE time_index > NOW() - INTERVAL '5 minutes'\r\nORDER BY time_index ASC;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Most Polluted Streets",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  streetname,\r\n  AVG(co2emission) AS \"avg_co2\"\r\nFROM\r\n  mtsumo_digital_twin.etvehicle\r\nWHERE\r\n  $__timeFilter(time_index)\r\n  AND streetname IS NOT NULL\r\n  AND streetname NOT LIKE ':%'  -- This will block ALL names starting with a colon\r\nGROUP BY\r\n  streetname\r\nORDER BY\r\n  avg_co2 DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Mean Speed of vehicules",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(time_index, $__interval) AS \"time\",\r\n  AVG(speed) AS avg_speed\r\nFROM\r\n  mtsumo_digital_twin.etvehicle\r\nWHERE\r\n  $__timeFilter(time_index)\r\nGROUP BY\r\n  1 -- Groups by the first column, which is \"time\"\r\nORDER BY\r\n  1; -- Orders by the first column"
    }
   ]
  },
  {
   "title": "Distribution of vehicule speeds",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT floor(speed) AS bucket,\r\n       COUNT(*) AS n\r\nFROM mtsumo_digital_twin.etvehicle\r\nWHERE time_index > NOW() - INTERVAL '5 minutes'\r\n  AND speed >= 0\r\n  AND speed < 8\r\nGROUP BY bucket\r\nORDER BY bucket;\r\n"
    }
   ]
  },
  {
   "title": "Average CO2 Emissions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(time_index, $__interval) AS \"time\",\r\n  AVG(co2emission) AS \"Average CO2 Emission\"\r\nFROM\r\n  mtsumo_digital_twin.etvehicle\r\nWHERE\r\n  $__timeFilter(time_index)\r\nGROUP BY\r\n  1\r\nORDER BY\r\n  1;"
    }
   ]
  }
 ]
}